name = "ink-packages-assets"
upload-to-group-id = 34772760

# Most projects will define some 'inputs'.
# This tells Tarmac where to find assets that we'll use in our game.
[[inputs]]
glob = "assets/images/**/*.png"
codegen = true
codegen-path = "src/shared/Assets/Images.lua"
codegen-base-path = "assets/images"
