[package]
name = "eduar/ink-packages"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
janitor = "howmanysmall/janitor@1.17.0"
vide = "centau/vide@0.3.1"
charm = "littensy/charm@0.9.0"
vide-charm = "littensy/vide-charm@0.2.0"
ui-labs = "pepeeltoro41/ui-labs@2.3.8"
